# Generated by Django 3.2.4 on 2021-07-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(max_length=100)),
                ('Car_model', models.CharField(max_length=100)),
                ('Car_Part_Name', models.CharField(max_length=100)),
                ('Car_Part_Info', models.CharField(choices=[('N', 'New'), ('U', 'USE')], max_length=50)),
                ('Car_Part_Cat', models.CharField(choices=[('E', 'Engine'), ('FS', 'Fuel System'), ('EX_S', 'Exhaust System'), ('CS', 'Colling System'), ('LS', 'Lubrication System'), ('EL_S', 'Electrical System'), ('T', 'Transmission'), ('C', 'Chassis')], max_length=50)),
                ('Car_Part_Discription', models.CharField(max_length=100)),
                ('Owner_info', models.CharField(max_length=200)),
            ],
        ),
    ]
