# Generated by Django 3.2.4 on 2021-08-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='user',
            new_name='suser',
        ),
    ]
